### ISSUE TITLE
Middleware doesn't seem to work

### ISSUE THREAD

**Issue by omerts** [icebob/moleculer-protect-services#2]
Hey,

I am so amazed by this amazing framework, wish I could give it a thousand stars. 
Just this module doesn't seem to be working, I have added the middleware, but it doesn't work. Tried adding it inside the service config, and also in moleculer.config.js. Seems that actions are not passed through it.

**Comment by icebob** [comment]
This middleware has been built for Moleculer v0.12 so maybe some parts should upgrade. I will check it.

**Comment by icebob** [comment]
I've upgraded the dependencies and it works without modification. Could you create a repro repo?

**Comment by omerts** [comment]
Sorry for not getting back to this :(, i guess this is stale by now. Closing...
